### ISSUE TITLE
Line 613: subprocess call fails

### ISSUE THREAD

**Issue by herrwusel** [tin2tin/Subtitle_Editor#5]
I get this on a linux system:
```
Python: Traceback (most recent call last):
  File "/home/jakob/.config/blender/3.6/scripts/addons/Subtitle_Editor-main/__init__.py", line 613, in execute
    subprocess.check_call(
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3.11', '-m', 'pip', 'install', '--no-warn-script-location', '--user']' returned non-zero exit status 1.
```
Is it possible that the call is just missing what to install https://github.com/tin2tin/Subtitle_Editor/blob/69c3aef89530521d5519c9810fbc96309f632af2/__init__.py#L613 ? For windows torch is installed.

**Comment by tin2tin** [comment]
Thanks, I don't have Linux, so I'll have to wait for someone to text in on Linux. And you're absolutely right, I forgot a line to install torch on Linux. I've updated the code. Thank you.

**Comment by herrwusel** [comment]
Thanks for the prompt fix. On many distros, this will fail due to [PEP 668](https://peps.python.org/pep-0668/). So a solution would be to test if the torch is available or else show the user a message to install it via the distro's package manager. For me it was just `pacman -S python-pytorch`. After removing the else part, your plugin works on Arch linux ;)

**Comment by tin2tin** [comment]
Thank you. I'm not sure, I understand the solution you suggest here, could you submit a patch?

**Comment by herrwusel** [comment]
I don't know about the blender interface, but basically something like this:
```python
        else:
            try:
                subprocess.check_call(
                    [
                        pybin,
                        "-m",
                        "pip",
                        "install",
                        "torch",
                        "--no-warn-script-location",
                        "--user",
                    ]
                    )
            except subprocess.CalledProcessError as e:
                print(e.returncode)
```
This code runs but is still missing some warning pop-up that informs the user about a missing dependency. Maybe I can come up with something on the weekend.
